#!/bin/bash

set -e

#python3 src/python/randy.py $@ -I include -ld -dynamic-linker /home/max/workspace/musl-1.2.4/lib/libc.so -lc

bin/randy $@ -I include -ld -dynamic-linker /home/max/workspace/musl-1.2.4/lib/libc.so -lc

